# Generated by Django 4.2.7 on 2025-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
